// Mocks generated by Mockito 5.4.6 from annotations
// in awesome_weather/test/features/forecast/presentation/bloc/forecast_list/forecast_list_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:awesome_weather/features/forecast/domain/entity/forecast_list_entity.dart'
    as _i2;
import 'package:awesome_weather/features/forecast/domain/entity/location_entity.dart'
    as _i6;
import 'package:awesome_weather/features/forecast/domain/usecase/get_forecast_list.dart'
    as _i3;
import 'package:awesome_weather/features/forecast/domain/usecase/get_location.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeForecastListEntity_0 extends _i1.SmartFake
    implements _i2.ForecastListEntity {
  _FakeForecastListEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetForecastList].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetForecastList extends _i1.Mock implements _i3.GetForecastList {
  MockGetForecastList() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ForecastListEntity> call({
    required double? latitude,
    required double? longitude,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #latitude: latitude,
              #longitude: longitude,
            }),
            returnValue: _i4.Future<_i2.ForecastListEntity>.value(
              _FakeForecastListEntity_0(
                this,
                Invocation.method(#call, [], {
                  #latitude: latitude,
                  #longitude: longitude,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.ForecastListEntity>);
}

/// A class which mocks [GetLocation].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetLocation extends _i1.Mock implements _i5.GetLocation {
  MockGetLocation() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i6.LocationEntity?> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i4.Future<_i6.LocationEntity?>.value(),
          )
          as _i4.Future<_i6.LocationEntity?>);
}
