// Mocks generated by Mockito 5.4.6 from annotations
// in awesome_weather/test/features/forecast/data/repository/forecast_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:awesome_weather/features/forecast/data/datasource/local_forecast_datasource.dart'
    as _i4;
import 'package:awesome_weather/features/forecast/data/datasource/network_forecast_datasource.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [NetworkForecastDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkForecastDatasource extends _i1.Mock
    implements _i2.NetworkForecastDatasource {
  MockNetworkForecastDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<Map<String, dynamic>> getForecastList({
    required double? latitude,
    required double? longitude,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getForecastList, [], {
              #latitude: latitude,
              #longitude: longitude,
            }),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> getDayForecast({
    required double? latitude,
    required double? longitude,
    required DateTime? date,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getDayForecast, [], {
              #latitude: latitude,
              #longitude: longitude,
              #date: date,
            }),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);
}

/// A class which mocks [LocalForecastDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalForecastDatasource extends _i1.Mock
    implements _i4.LocalForecastDatasource {
  MockLocalForecastDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> cacheData({
    required String? path,
    required double? latitude,
    required double? longitude,
    required Map<String, dynamic>? data,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#cacheData, [], {
              #path: path,
              #latitude: latitude,
              #longitude: longitude,
              #data: data,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  Map<String, dynamic>? getCachedData({
    required String? path,
    required double? latitude,
    required double? longitude,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedData, [], {
              #path: path,
              #latitude: latitude,
              #longitude: longitude,
            }),
          )
          as Map<String, dynamic>?);
}
